backend:
  name: github 
  repo: thriken/thriken.github.io
  branch: master      

  
media_folder: "static/images" 
public_folder: "/images"      

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"   # 内容文件存储目录
    create: true              # 允许创建新文件
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
